from interpreter import Parser, Interpreter
from interpreter import Lexer

lexer = Lexer()
#lexer.init("2 + 2 - 4 + 3")
lexer.init("BEGIN x := 10; y := x + 2 * (3 - 1); END.")
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
print(lexer.next())
# parser = Parser()
# print(parser.eval("BEGIN x := 10; y := x + 2 * (3 - 1); END."))

interp = Interpreter()
print(interp.eval('''BEGIN y:= 2; BEGIN a := 3; a := a; b := 10 + a + 10 * y / 4; c := a - b; END; x := 11; END.'''))